name: Auto-Assign Second Reviewer

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto_assign_reviewer:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if PR needs second reviewer
        id: check_needs_second_reviewer
        run: |
          if: steps.check_approval.outputs.approved == 'true'
          SECOND_REVIEWER="fivetran-joemarkiewicz"
          echo "second_reviewer=$SECOND_REVIEWER" >> $GITHUB_OUTPUT
          PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
          CURRENT_REVIEWERS=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
                              -H "Accept: application/vnd.github.v3+json" \
                              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers" | jq -r '.[] | .login')
          
          if [[ ! "$CURRENT_REVIEWERS" =~ "$SECOND_REVIEWER" ]]; then
            NEEDS_SECOND_REVIEWER="true"
          else
            NEEDS_SECOND_REVIEWER="false"
          fi
          echo "needs_second_reviewer=$NEEDS_SECOND_REVIEWER" >> $GITHUB_OUTPUT

      - name: Assign Second Reviewer
        if: steps.check_needs_second_reviewer.outputs.needs_second_reviewer == 'true'
        run: |
          PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
          SECOND_REVIEWER=${{ steps.check_needs_second_reviewer.outputs.second_reviewer }}
          curl -X POST \
               -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -d "{\"reviewers\": [\"$SECOND_REVIEWER\"]}" \
               "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers"
