# .github/workflows/trigger_release.yml
name: Trigger Release

on:
  pull_request:
    types:
      - closed      # Merged to main
      - labeled     # Pre-release tag added

jobs:
  release:
    if: |
      github.event.pull_request.merged == true ||
      github.event.label.name == 'pre-release'
    uses: fivetran-catfritz/release_tester/.github/workflows/update-test.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
